trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

stage: 
    jobs:
      - job: sync
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                chmod +x pipelines-sync/
                ./pipeline-sync/sync-commit.yml