trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: SyncStage
    jobs:
      - job: sync
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                export BRANCH_NAME=${BRANCH} 
                chmod +x pipelines-sync/sync-commit.sh
                ./pipelines-sync/sync-commit.sh
            env:
              BRANCH_NAME: $(Build.SourceBranchName)
