trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Bash@3
    displayName: 'synchronizing the commits'
    inputs:
      targetType: 'inline'
      script: |
        chmod +x ./sync-commit.sh
        ./sync-commit.sh